name: Build debian packages for release 

on:
  push:
    branches:
      - build

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  debian-package:
    name: "Build debian packages"
    runs-on: ubuntu-latest
    environment:
      name: "release"
    container:
      image: "debian:bullseye"
    steps:
      - name: Install dependencies
        shell: bash
        run: |
          echo -e 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";' >/etc/apt/apt.conf.d/99hst
          apt-get update
          apt-get -y upgrade
          apt-get -y install devscripts dpkg-dev debhelper equivs curl git
      - name: Enable proxmox apt repo
        run: |
          echo "deb http://download.proxmox.com/debian bullseye pve-no-subscription" > /etc/apt/sources.list.d/proxmox.list
          echo "deb http://download.proxmox.com/debian/devel bullseye main" >> /etc/apt/sources.list.d/proxmox.list
          curl -1sLf http://download.proxmox.com/debian/proxmox-release-bullseye.gpg -o /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
          apt-get -y update
      - name: Set package priority
        shell: bash
        run: |
          echo -e 'Package: librust-aho-corasick*\nPin: version 0.7*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-async-trait*\nPin: version 0.1.24*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-backtrace+backtrace-sys-dev\nPin: version 0.3.44*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-backtrace+default-dev\nPin: version 0.3.44*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-backtrace-dev\nPin: version 0.3.44*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-generic-array-dev\nPin: version 0.14.4*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-half-dev\nPin: version 1.6*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-handlebars-dev\nPin: version 3.0.1*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-idna-dev\nPin: version 0.2*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-libloading-dev\nPin: version 0.6*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-nix-dev\nPin: version 0.26*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-pest*\nPin: version 2.1*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-apt*\nPin: version 0.10.2*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-auth-api*\nPin: version 0.3.0*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-compression*\nPin: version 0.2.1*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-http*\nPin: version 0.9.0*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-human-byte*\nPin: version 0.1.0*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-ldap-dev*\nPin: version 0.2.1*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-metrics*\nPin: version 0.3.0*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-openid*\nPin: version 0.10.0*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-rest-server*\nPin: version 0.4.1*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-rest-server-dev\nPin: version 0.4.1-1*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-shared-memory*\nPin: version 0.3.0*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-subscription*\nPin: version 0.4.0*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-sys*\nPin: version 0.5.0*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-proxmox-tfa*\nPin: version 4.0.2*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-rustyline*\nPin: version 9.1.2-1~bpo11+pve2\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-spin-dev\nPin: version 0.5*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
          echo -e 'Package: librust-xattr-dev\nPin: version 0.2*\nPin-Priority: 600\n' > /etc/apt/preferences.d/proxmox.pref
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: source
      - name: Build package
        working-directory: source
        run: |
          apt-get -y install cargo
          mk-build-deps -i -r -t "apt-get -o Debug::pkgProblemResolver=yes -y --no-install-recommends"
          export BUILD_MODE=release
          dpkg-buildpackage -b -us -uc -rfakeroot
      - uses: actions/upload-artifact@v3
        with:
          name: Debian packages
          path: ./*.deb
